### ISSUE TITLE
Problema en el paso 2 de registro de usuarios

### ISSUE THREAD

**Issue by Gabinsito** [UNIZAR-30226-2022-05/Backend#3]
Cuando pones un código que no es convertible a entero el backend peta y devuelve error 400. Creo que sería tan fácil como poner un try-catch y en caso de que no se pueda convertir a entero, devuelva un error de tipo: "El código no cumple el formato" o algo del estilo.

**Comment by Gabinsito** [comment]
También se podría controlar desde el frontend. Pero como no estoy seguro de qué es mejor opción lo pongo por aquí

**Comment by RIranzo** [comment]
Creo que sería mejor y más sencillo evitar que se pueda meter algo distinto a un número desde el frontend, pues en el backend no se produce una excepción sino un warning cuando Spring hace la conversión automática a Integer, y no se muy bien cómo capturar eso. Así nos ahorramos una llamada para una comprobación que puede hacer el frontend.
